@startuml
package controller {
    class StudentController {
        +viewEntranceTestInfo()
    }
}

package repository {
    class DatabaseRepo {
        +queryEntranceTestInfo()
    }

package entity {
    class Test {
        +id: int
        +date: Date
        +venue: String
    }
}

StudentController --> DatabaseRepo : uses
DatabaseRepo --> Test : returns
@enduml