@startuml
package controller {
    class StudentController {
        +viewEntranceTestInfo()
    }
}

package repository {
    class TestRepo {
        +queryEntranceTestInfo()
    }

package entity {
    class Test {
        +id: int
        +date: Date
        +venue: String
    }
}

StudentController --> TestRepo : uses
TestRepo --> Test : returns
@enduml