@startuml
package controller {
    class StudentController {
        +searchApplication()
    }
}

package repository {
    class DatabaseRepo {
        +querySearchApplication()
    }
}

package entity {
    class Application {
        +id: int
        +date: Date
        +status: String
    }
}

StudentController --> DatabaseRepo : uses
DatabaseRepo --> Application : returns
@enduml
