@startuml
package controller {
    class StudentController {
        +searchApplication()
    }
}

package repository {
    class ApplicationRepo {
        +querySearchApplication()
    }
}

package entity {
    class Application {
        +id: int
        +date: Date
        +status: String
    }
}

StudentController --> ApplicationRepo : uses
ApplicationRepo --> Application : returns
@enduml
